defaults:
  # - hurti_config
  - _self_

wandb_logging: True
wandb_tag: "test"
wandb_group: experiment_1
log_path: /home/ruoxi/vo_rl/logs/log_voRL/training
n_envs: 51
total_timesteps: 25e6
val_interval: 10

eval_log: '/home/ruoxi/vo_rl/logs/log_voRL/playground/${now:%Y-%m-%d_%H-%M-%S}'
# weight_path : '/home/ruoxi/vo_rl/logs/log_voRL/training/experiment_1/Sep08_01-21-36_test/Policy/iter_00020.pth'
weight_path : '/home/ruoxi/vo_rl/logs/log_voRL/training/experiment_1/Sep08_05-22-30_test/Policy/iter_00040.pth'
use_rl_actions: False
max_eval_steps: -1  # -1 if maximum length of trajectories should be taken
visualize_trajs: False
use_gt_initialization: False
vo_algorithm: "SVO"
test_seq_ids: -1 # -1 for all test sequences

# Uncomment the wanted dataset and set the correct paths
#dataset: 'euroc'
#dataset_dir: "/datasets/EuRoC"
#svo_params_file: "<path>/svo-lib/svo_env/param/euroc.yaml"
#svo_calib_file: "/datasets/EuRoC/calibration/euroc_mono.yaml"
#nr_seqs: 11

dataset: 'tum'
dataset_dir: "/home/ruoxi/datasets/TUM-RGBD"
svo_calib_file: "/home/ruoxi/vo_rl/svo-lib/svo_env/param/calib/svo_tartanair_pinhole.yaml"
svo_params_file: "/home/ruoxi/vo_rl/svo-lib/svo_env/param/tartan_test.yaml"
nr_seqs: 1

agent:
  n_epochs: 10
  gae_lambda: 0.95
  gamma: 0.6
  n_steps: 250
  ent_coef: 0.0025
  vf_coef: 0.5
  max_grad_norm: 0.5
  batch_size: 25000
  use_sde: False
  reward:
    align_reward: 0.01
    keyframe_reward: 0.0001
    traj_length: 5
    nr_points_for_align: 3