# Deactivate hydra logging
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .
# End Deactivate hydra logging

wandb_logging: True
wandb_tag: "test"
wandb_group: experiment_1
log_path: /home/ruoxi/vo_rl/logs/log_voRL/training
n_envs: 51
seed: 0
total_timesteps: 25e6

val_interval: 10

dataset_dir: "/home/ruoxi/datasets/TartanAir/"
dataset_name: "tartanair"
vo_algorithm: "SVO"
svo_params_file: "/home/ruoxi/vo_rl/svo-lib/svo_env/param/tartan_train.yaml"
svo_calib_file: "/home/ruoxi/vo_rl/svo-lib/svo_env/param/calib/svo_tartanair_pinhole.yaml"

# null if train from scratch, get new policy
# policy_path: null

# continue use the policy former training
policy_path: "/home/ruoxi/vo_rl/logs/log_voRL/training/experiment_1/Sep08_01-21-36_test/Policy/iter_00020.pth"

agent:
  n_epochs: 3
  gae_lambda: 0.95
  gamma: 0.6
  n_steps: 250
  ent_coef: 0.0025
  vf_coef: 0.5
  max_grad_norm: 0.5
  batch_size: 25000
  use_sde: False
  reward:
    align_reward: 0.01
    keyframe_reward: 0.0001
    traj_length: 5
    nr_points_for_align: 3
